(part "MP002808"
    (packageRef "MP002808")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "Multicomp Pro")
    (property "Manufacturer_Part_Number" "MP002808")
    (property "Description" "MULTICOMP PRO MP002808Power Inductor (SMD), 100 H, 3 A, Unshielded")
    (property "Datasheet_Link" "")
    (property "symbolName1" "MP002808")
)
