(part "CTB0308_2"
    (packageRef "CTB03082")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "CAMDENBOSS")
    (property "Manufacturer_Part_Number" "CTB0308/2")
    (property "Description" "TERMINAL BLOCK, WIRE TO BRD, 2POS, 16AWG")
    (property "Datasheet_Link" "")
    (property "symbolName1" "CTB0308_2")
)
